### ISSUE TITLE
arg-extract-tmrca command not found

### ISSUE THREAD

**Issue by chaturvedi-lab** [mdrasmus/argweaver#34]
Hi Rasmus,

I was implementing argweaver by doing a conda install. While my arg-sample command works, my arg-extract-tmrca command does not work. Do you have any solutions?

Samridhi

**Comment by maccalvert** [comment]
I came across this same problem. I fixed it by running python2 instead of 3. Maybe you found a solution already, but leaving this fix in case anyone else encounters this problem. 

P.S. Hi Sam! hope you're doing well!

**Comment by ktmeaton** [comment]
I can also confirm that using python2 fixed this problem for me. Here is my conda `environment.yml` file:

```yaml
name: argweaver
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=2.7
  - pip
  - pip:
    - "git+https://github.com/mdrasmus/argweaver.git@fee3d32c"

```
